### ISSUE TITLE
TypeError: Error processing argument at index 10, conversion failure from ./icon.png

### ISSUE THREAD

**Issue by johanlunds** [headsetapp/headset-electron#253]
### Description

I get this error message fairly often, but quite randomly. It does NOT crash the process. It still works. But is quite annoying.

Error message:

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 10, conversion failure from ./icon.png
    at Object.showMessageBox (/Applications/Headset.app/Contents/Resources/electron.asar/browser/api/dialog.js:278:20)
    at AutoUpdater.updateDownloaded (/Applications/Headset.app/Contents/Resources/app.asar/node_modules/headset-autoupdater/index.js:31:12)
    at GhReleases.<anonymous> (/Applications/Headset.app/Contents/Resources/app.asar/node_modules/headset-autoupdater/index.js:21:53)
    at GhReleases.emit (events.js:194:13)
    at AutoUpdater.<anonymous> (/Applications/Headset.app/Contents/Resources/app.asar/node_modules/electron-gh-releases/GhReleases.js:44:19)
    at AutoUpdater.emit (events.js:194:13)
```

See screenshot.

### Your Environment

- OS: Mac
- Headset version: latest 2.2.0

### Screenshots

<img width="420" alt="Blank_Skitch_Document" src="https://user-images.githubusercontent.com/22144/61065895-db71bf00-a404-11e9-9b96-aacb53ad0e52.png">

**Comment by fcastilloec** [comment]
This has been fixed in a new version that will be released later today. Sorry about it
