### ISSUE TITLE
Build for arm64 / silicon mac

### ISSUE THREAD

**Issue by mayel** [headsetapp/headset-electron#491]
👋 nice app! would be nice to have a native build on the new macs

**Comment by fcastilloec** [comment]
We're considering this. Right now some of the code specific for mac (controlling Headset from the "Now Playing" widget) uses native code that needs compiling on an arm64 mac. I don't have a mac to test this, so it probably won't happen any time soon.

**Comment by fcastilloec** [comment]
@mayel Would you be willing to test some builds for `arm64` on macOS?

**Comment by mayel** [comment]
Sure!

**Comment by fcastilloec** [comment]
Here's a WeTransfer link https://we.tl/t-w1K7xYUCe2
The file is too big to be share here, sorry.

The installer is also not signed, so I hope that's not a problem for you. Let me know if everything is working as excepted, especially controlling the app through the "Now Playing" widget of macOS.

**Comment by mayel** [comment]
@fcastilloec the app doesn't launch, here is what I see searching for "headset" in the console, let me know what other logs wold be helpful:

```
default	12:18:26.918422+1200	runningboardd	Launch request for app<application.co.headsetapp.app.33248774.33248981(501)> is using uid 501 (divined from auid 501 euid 501)
default	12:18:26.918715+1200	runningboardd	Acquiring assertion targeting app<application.co.headsetapp.app.33248774.33248981(501)> from originator [daemon<com.apple.Dock.agent(501)>:581] with description <RBSAssertionDescriptor| "LS launch co.headsetapp.app" ID:397-581-159029 target:app<application.co.headsetapp.app.33248774.33248981(501)> attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LaunchRoleUserInteractive" sourceEnvironment:"(null)">
	]>
default	12:18:26.918962+1200	runningboardd	Assertion 397-581-159029 (target:app<application.co.headsetapp.app.33248774.33248981(501)>) will be created as active
default	12:18:26.919239+1200	runningboardd	Executing launch request for app<application.co.headsetapp.app.33248774.33248981(501)> (LS launch co.headsetapp.app)
default	12:18:26.919450+1200	runningboardd	Creating and launching job for: app<application.co.headsetapp.app.33248774.33248981(501)>
default	12:18:26.919569+1200	runningboardd	_mutateContextIfNeeded called for co.headsetapp.app
default	12:18:26.930643+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] This process will not be managed.
default	12:18:26.930686+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] HOME is <private>
default	12:18:26.930721+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] TMPDIR is <private>
default	12:18:26.930759+1200	runningboardd	Now tracking process: [app<application.co.headsetapp.app.33248774.33248981(501)>:34492]
default	12:18:26.930870+1200	runningboardd	Using default underlying assertion for app: [app<application.co.headsetapp.app.33248774.33248981(501)>:34492]
default	12:18:26.930891+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: running-active (role: UserInteractive)
default	12:18:26.930988+1200	runningboardd	Acquiring assertion targeting [app<application.co.headsetapp.app.33248774.33248981(501)>:34492] from originator [app<application.co.headsetapp.app.33248774.33248981(501)>:34492] with description <RBSAssertionDescriptor| "RB Underlying Assertion" ID:397-397-159030 target:34492 attributes:[
	<RBSDomainAttribute| domain:"com.apple.underlying" name:"defaultUnderlyingAppAssertion" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
default	12:18:26.931123+1200	runningboardd	Assertion 397-397-159030 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) will be created as active
default	12:18:26.931327+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring jetsam update because this process is not memory-managed
default	12:18:26.931427+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring suspend because this process is not lifecycle managed
default	12:18:26.931627+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Set darwin role to: UserInteractive
default	12:18:26.931835+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring GPU update because this process is not GPU managed
default	12:18:26.932596+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: running-active (role: UserInteractive)
default	12:18:26.933125+1200	runningboardd	Acquiring assertion targeting [app<application.co.headsetapp.app.33248774.33248981(501)>:34492] from originator [daemon<com.apple.coreservices.launchservicesd>:358] with description <RBSAssertionDescriptor| "foregroundApp:34492" ID:397-358-159031 target:34492 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractiveNonFocal" sourceEnvironment:"(null)">
	]>
default	12:18:26.933489+1200	runningboardd	Assertion 397-358-159031 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) will be created as active
default	12:18:26.935384+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: running-active (role: UserInteractive)
default	12:18:26.935750+1200	runningboardd	Acquiring assertion targeting [app<application.co.headsetapp.app.33248774.33248981(501)>:34492] from originator [daemon<com.apple.coreservices.launchservicesd>:358] with description <RBSAssertionDescriptor| "foregroundApp:34492" ID:397-358-159032 target:34492 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractiveNonFocal" sourceEnvironment:"(null)">
	]>
default	12:18:26.936003+1200	runningboardd	Assertion 397-358-159032 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) will be created as active
default	12:18:26.936789+1200	runningboardd	Invalidating assertion 397-358-159031 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) from originator [daemon<com.apple.coreservices.launchservicesd>:358]
default	12:18:26.937330+1200	runningboardd	Acquiring assertion targeting [app<application.co.headsetapp.app.33248774.33248981(501)>:34492] from originator [daemon<com.apple.coreservices.launchservicesd>:358] with description <RBSAssertionDescriptor| "foregroundApp:34492" ID:397-358-159033 target:34492 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractiveNonFocal" sourceEnvironment:"(null)">
	]>
default	12:18:26.937436+1200	runningboardd	Assertion 397-358-159033 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) will be created as active
default	12:18:26.938693+1200	runningboardd	Invalidating assertion 397-358-159032 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) from originator [daemon<com.apple.coreservices.launchservicesd>:358]
default	12:18:26.943212+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] reported to RB as running
default	12:18:26.945230+1200	runningboardd	Acquiring assertion targeting [app<application.co.headsetapp.app.33248774.33248981(501)>:34492] from originator [daemon<com.apple.coreservices.appleevents(55)>:514] with description <RBSAssertionDescriptor| "AE/Headset" ID:397-514-159034 target:34492 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>
default	12:18:26.945338+1200	runningboardd	Assertion 397-514-159034 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) will be created as active
default	12:18:26.946593+1200	runningboardd	Invalidating assertion 397-581-159029 (target:app<application.co.headsetapp.app.33248774.33248981(501)>) from originator [daemon<com.apple.Dock.agent(501)>:581]
default	12:18:26.946696+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: running-active (role: UserInteractive)
default	12:18:26.942235+1200	Dock	LAUNCH: 0x0-0x3299296 co.headsetapp.app starting stopped process.
default	12:18:26.946479+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring jetsam update because this process is not memory-managed
default	12:18:26.947020+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring suspend because this process is not lifecycle managed
default	12:18:26.947061+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring GPU update because this process is not GPU managed
default	12:18:26.947185+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring jetsam update because this process is not memory-managed
default	12:18:26.947220+1200	runningboardd	Successfully acquired underlying assertion for [app<application.co.headsetapp.app.33248774.33248981(501)>:34492]
default	12:18:26.947385+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring suspend because this process is not lifecycle managed
default	12:18:26.947820+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring GPU update because this process is not GPU managed
default	12:18:26.948681+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring jetsam update because this process is not memory-managed
default	12:18:26.948961+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring suspend because this process is not lifecycle managed
default	12:18:26.949435+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring GPU update because this process is not GPU managed
default	12:18:26.973465+1200	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Headset, ready, updating active tracking timer
default	12:18:26.973499+1200	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Headset
default	12:18:27.045972+1200	tccd	AUTHREQ_ATTRIBUTION: msgID=34492.1, attribution={requesting={<TCCDProcess: identifier=Electron, pid=34492, auid=501, euid=501, binary_path=/Applications/Headset.app/Contents/MacOS/Headset>}, },
default	12:18:27.048857+1200	tccd	AUTHREQ_SUBJECT: msgID=34492.1, subject=co.headsetapp.app,
default	12:18:27.050101+1200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier co.headsetapp.app, type: 0: 0x123af5680 at /Applications/Headset.app
default	12:18:27.053395+1200	tccd	AUTHREQ_ATTRIBUTION: msgID=387.4094, attribution={accessing={<TCCDProcess: identifier=Electron, pid=34492, auid=501, euid=501, binary_path=/Applications/Headset.app/Contents/MacOS/Headset>}, requesting={<TCCDProcess: identifier=com.apple.WindowServer, pid=387, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer>}, },
default	12:18:27.053497+1200	tccd	requestor: <TCCDProcess: identifier=com.apple.WindowServer, pid=387, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer> is checking access for accessor <TCCDProcess: identifier=Electron, pid=34492, auid=501, euid=501, binary_path=/Applications/Headset.app/Contents/MacOS/Headset>
default	12:18:27.055284+1200	tccd	AUTHREQ_SUBJECT: msgID=387.4094, subject=co.headsetapp.app,
default	12:18:27.056760+1200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier co.headsetapp.app, type: 0: 0x12274b780 at /Applications/Headset.app
default	12:18:27.078077+1200	Headset	CHECKIN: pid=34492
default	12:18:27.080404+1200	launchservicesd	CHECKIN:0x0-0x3299296 34492 co.headsetapp.app
default	12:18:27.080538+1200	Headset	CHECKEDIN: pid=34492 asn=0x0-0x3299296 foreground=1
default	12:18:27.080971+1200	lockoutagent	Requesting policy for bundle IDs: (
    "co.headsetapp.app"
)
default	12:18:27.081585+1200	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Headset
default	12:18:27.081515+1200	Headset	FRONTLOGGING: version 1
default	12:18:27.081538+1200	Headset	Registered, pid=34492 ASN=0x0,0x3299296
default	12:18:27.083152+1200	Headset	BringForward: pid=34492 asn=0x0-0x3299296 bringForward=1 foreground=1 uiElement=0 launchedByLS=1 modifiersCount=1 allDisabled=0
default	12:18:27.083214+1200	Headset	BringFrontModifier: pid=34492 asn=0x0-0x3299296 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	12:18:27.083247+1200	Headset	BringForward: pid=34492 asn=0x0-0x3299296
default	12:18:27.083283+1200	Headset	SetFrontProcess: asn=0x0-0x3299296 options=0
default	12:18:27.088680+1200	Headset	Current system appearance, (HLTB: 2), (SLS: 1)
default	12:18:27.091769+1200	Headset	Post-registration system appearance: (HLTB: 2)
default	12:18:27.097656+1200	runningboardd	Acquiring assertion targeting [app<application.co.headsetapp.app.33248774.33248981(501)>:34492] from originator [daemon<com.apple.coreservices.launchservicesd>:358] with description <RBSAssertionDescriptor| "frontmost:34492" ID:397-358-159035 target:34492 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractiveFocal" sourceEnvironment:"(null)">
	]>
default	12:18:27.097723+1200	runningboardd	Assertion 397-358-159035 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) will be created as active
default	12:18:27.097820+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring jetsam update because this process is not memory-managed
default	12:18:27.097835+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring suspend because this process is not lifecycle managed
default	12:18:27.097840+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: running-active (role: UserInteractiveNonFocal)
default	12:18:27.097856+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Set darwin role to: UserInteractiveNonFocal
default	12:18:27.097875+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring GPU update because this process is not GPU managed
default	12:18:27.098648+1200	runningboardd	Acquiring assertion targeting [app<application.co.headsetapp.app.33248774.33248981(501)>:34492] from originator [daemon<com.apple.WindowServer(88)>:387] with description <RBSAssertionDescriptor| "FUSBFrontmostProcess" ID:397-387-159036 target:34492 attributes:[
	<RBSDomainAttribute| domain:"com.apple.fuseboard" name:"Frontmost" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
default	12:18:27.098777+1200	runningboardd	Assertion 397-387-159036 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) will be created as active
default	12:18:27.098656+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring jetsam update because this process is not memory-managed
default	12:18:27.098992+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: running-active (role: UserInteractiveFocal)
default	12:18:27.098908+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring suspend because this process is not lifecycle managed
default	12:18:27.099294+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Set darwin role to: UserInteractiveFocal
default	12:18:27.099323+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: running-active (role: UserInteractiveFocal)
default	12:18:27.099358+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring GPU update because this process is not GPU managed
default	12:18:27.099692+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring jetsam update because this process is not memory-managed
default	12:18:27.099805+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring suspend because this process is not lifecycle managed
default	12:18:27.099848+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring GPU update because this process is not GPU managed
default	12:18:27.100332+1200	runningboardd	Acquiring assertion targeting [app<application.co.headsetapp.app.33248774.33248981(501)>:34492] from originator [daemon<com.apple.coreservices.launchservicesd>:358] with description <RBSAssertionDescriptor| "notification:34492" ID:397-358-159037 target:34492 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>
default	12:18:27.100441+1200	runningboardd	Assertion 397-358-159037 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) will be created as active
default	12:18:27.100792+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: running-active (role: UserInteractiveFocal)
default	12:18:27.100809+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring jetsam update because this process is not memory-managed
default	12:18:27.100846+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring suspend because this process is not lifecycle managed
default	12:18:27.100868+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] Ignoring GPU update because this process is not GPU managed
default	12:18:27.105003+1200	lockoutagent	Requested application co.headsetapp.app has policy OK, associated categories:DH1003 associated sites:(null) equivalent bundle identifiers:co.headsetapp.app
default	12:18:27.109807+1200	Headset	Received configuration update from daemon (initial)
default	12:18:27.114815+1200	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: co.headsetapp.app token: 1e00000021 pid: 34492
default	12:18:27.394330+1200	Headset	Entering exit handler.
default	12:18:27.394359+1200	Headset	Exiting exit handler.
default	12:18:27.398720+1200	runningboardd	Invalidating assertion 397-358-159037 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) from originator [daemon<com.apple.coreservices.launchservicesd>:358]
default	12:18:27.411473+1200	runningboardd	[app<application.co.headsetapp.app.33248774.33248981(501)>:34492] termination reported by launchd (0, 0, 0)
default	12:18:27.413575+1200	runningboardd	Removing process: [app<application.co.headsetapp.app.33248774.33248981(501)>:34492]
default	12:18:27.413932+1200	runningboardd	Removing launch job for: [app<application.co.headsetapp.app.33248774.33248981(501)>:34492]
default	12:18:27.414237+1200	runningboardd	Invalidating assertion 397-387-159036 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492]) from originator [daemon<com.apple.WindowServer(88)>:387]
default	12:18:27.414273+1200	runningboardd	Removed job for [app<application.co.headsetapp.app.33248774.33248981(501)>:34492]
default	12:18:27.414302+1200	runningboardd	Removing assertions for terminated process: [app<application.co.headsetapp.app.33248774.33248981(501)>:34492]
default	12:18:27.414386+1200	runningboardd	Removed last relative-start-date-defining assertion for process app<application.co.headsetapp.app.33248774.33248981(501)>
default	12:18:27.432682+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: none (role: None)
default	12:18:27.433243+1200	runningboardd	Calculated state for app<application.co.headsetapp.app.33248774.33248981(501)>: none (role: None)
default	12:18:27.434226+1200	launchservicesd	Hit the server for a process handle 89faf74000086bc that resolved to: [app<application.co.headsetapp.app.33248774.33248981(501)>:34492]
default	12:18:27.436391+1200	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Headset, _appTrackingState = 2
default	12:18:27.436424+1200	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: Headset, quit, updating active tracking timer
error	12:18:27.517213+1200	runningboardd	RBSStateCapture remove item called for untracked item 397-387-159036 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492])
error	12:18:27.517271+1200	runningboardd	RBSStateCapture remove item called for untracked item 397-358-159037 (target:[app<application.co.headsetapp.app.33248774.33248981(501)>:34492])
```

**Comment by fcastilloec** [comment]
Does Headset produce any logs itself? Our logs are located in `~/Library/Logs/Headset/main.log` on macOS. Logs are also re-written every time you open the app.
If our logs are empty, perhaps I can send you a new build that doesn't use the native code and see if that helps.
I'm also considering adding an extra Github Action flow, so the builds are produced directly there and installers are available right away, instead of having me using third-party sharing apps.

**Comment by mayel** [comment]
Oh looks like it's the wrong architecture?
```
2022-06-25 13:32:31.762		 Error: dlopen(/var/folders/16/cjghq6k13s72qx7hsxnx8r_m0000gn/T/.co.headsetapp.app.BBHdWs, 0x0001): tried: '/var/folders/16/cjghq6k13s72qx7hsxnx8r_m0000gn/T/.co.headsetapp.app.BBHdWs' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/private/var/folders/16/cjghq6k13s72qx7hsxnx8r_m0000gn/T/.co.headsetapp.app.BBHdWs' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1143:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/Applications/Headset.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Applications/Headset.app/Contents/Resources/app.asar/node_modules/electron-media-service/src/darwin/index.js:1:51)
```

**Comment by fcastilloec** [comment]
Thanks so much for the logs! It seems that `electron-media-service` is causing the problem, which I already predicted. This is used by the "Now Playing" widget.
I'm currently making some changes so I don't have to use WeTransfer to share test builds. Once that's done, I'll create a new build without that code so you can test the new installer. It'll probably be done over the weekend.

Thanks again for helping test and debug this! 😄

**Comment by fcastilloec** [comment]
Here's a new build that hopefully fixes the error. I'm still not sure if it will, since rebuilding for a different architecture that's not the one your system is running on hasn't always worked for me, so 🤞🏼
If this new build doesn't work either. I'm tempted to remove the offending package, at least to test if the regular code still works as it should. Let me know how it goes, and please share the Headset log file, since the console output is not really helpful in this case.
https://github.com/headsetapp/headset-electron/suites/7087206343/artifacts/280119071

**Comment by mayel** [comment]
It works! 🔥 

<img width="556" alt="Screenshot 2022-06-25 at 19 21 41" src="https://user-images.githubusercontent.com/115318/175763180-d3b23885-b504-4955-82bd-26f32a205830.png">

**Comment by fcastilloec** [comment]
Can you test the "Now Playing" widget? Specifically, test if you can skip to any specific time on a song.
The "Now Playing" widget is found under the menu bar, it's not our widget with the Headset icon, it's the built-in one. If you have multiple apps playing media, you'll see them all there. Make sure you expand Headset so you can see the progress bar and test moving it back and forward and then report back.

Here's an image I found online that can help you find it.
![out](https://user-images.githubusercontent.com/1280530/175764817-ff4c2a25-ca05-48e6-afbd-2daf4e4fa55c.jpg)


 I think you can also see it under the control center:
![Control-Center-macOS-Big-Sur-Cropped](https://user-images.githubusercontent.com/1280530/175764686-053e3efb-55b1-4659-b55a-fce209cdaf02.jpg)

**Comment by mayel** [comment]
Ah I indeed confused it with Headset's own menu. Yeah I can play/pause and scrub! The back/forward buttons are disabled though.

**Comment by fcastilloec** [comment]
That is great news! Back/forward buttons don't work. Given that our data comes directly from Youtube, our playlist are not the same as what a traditional music player deals with, so going to the next or previous song is not treated by the system in the same way. Perhaps there might be a way to do it, but it's outside the scope of my knowledge.

Thanks so much for testing! I'll clean up the code and include these changes to the main branch. I'm not sure if we'll release a new version soon. We're trying to deal with notarizing the app for macOS before we release a new version and that's taking longer than expected.

I'll close this issue once I get a PR merged

**Comment by mayel** [comment]
Awesome, thank you! glad to have been of help
