### ISSUE TITLE
A JavaScript error has occured in the main process

### ISSUE THREAD

**Issue by harishr1308** [headsetapp/headset-electron#88]
### Description
An error box has appeared which skips the music from my Likes list

### Expected behaviour
Playing Music from my likes without this error

### Actual behaviour
Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at EventEmitter.ipcMain.on (/usr/lib/Headset/resources/app/index.js:130:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/usr/lib/Headset/resources/electron.asar/browser/api/web-contents.js:240:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

### Your Environment
Ubuntu 17.10
Headset version:
Core: 1.3.5, Wrapper: v1.5.2

### Screenshots
For some reason even I'm having a hard time recreating this issue.
I fixed it by restarting the application.
🖼

**Comment by danielravina** [comment]
Hi! 

Please update to the latest Ubuntu build (1.6.1) 
- Download the .deb from
https://github.com/headsetapp/headset-electron/releases/download/v1.6.1/headset_1.6.1_amd64.deb
or use the APT repository:
https://github.com/headsetapp/headset-electron#debian
